<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>302ef823-f5b8-412b-9454-a94988e0aa7c</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

</Project>
